# main dir: /frontend
# dist dir: /frontend/dist

FROM node:25.1-alpine AS builder
WORKDIR /frontend
COPY ./package*.json /frontend
RUN npm install --force
COPY . /frontend
RUN npm run build

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80/tcp
CMD ["nginx", "-g", "daemon off;"]