FROM python:3.14

WORKDIR /api

RUN python3 -m pip install --upgrade pip

COPY ./requirements-dev.txt /api/requirements-dev.txt
RUN python3 -m pip install --no-cache-dir --upgrade -r /api/requirements-dev.txt

COPY ./requirements-prod.txt /api/requirements-prod.txt
RUN python3 -m pip install --no-cache-dir --upgrade -r /api/requirements-prod.txt

COPY ./app /api/app

CMD ["python3", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]