FROM python:3.14

WORKDIR /api

RUN python3 -m pip install --upgrade pip

COPY ./requirements-prod.txt /api/requirements-prod.txt
RUN python3 -m pip install --no-cache-dir --upgrade -r /api/requirements-prod.txt

COPY ./app /api/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]